# PTR- och A-records for home.lan hosts
# Maintained by: Yasse / 2026-03-16
# Format PTR: local-data-ptr "IP" "hostname"
# Format A:   local-data: "hostname. A IP"

server:
  # Auktoritativ zon för home.lan
  local-zone: "home.lan." static

  # 192.168.1.x — Main LAN

  local-data-ptr: "192.168.1.1    udr7.home.lan"
  local-data-ptr: "192.168.1.55   pi.home.lan"
  local-data-ptr: "192.168.1.78   mbp.home.lan"
  local-data-ptr: "192.168.1.86   macmini.home.lan"

  # 192.168.40.x — MLO/WiFi
  local-data-ptr: "192.168.40.207 iphone.home.lan"

  # fd12:3456:7801::/64 — ULA Main LAN (IPv6 PTR)
  local-data-ptr: "fd12:3456:7801::55 pi.home.lan"
  local-data-ptr: "fd12:3456:7801::86 macmini.home.lan"
  local-data-ptr: "fd12:3456:7801::78 mbp.home.lan"
